# -*- coding: utf-8 -*-
"""
gdi.py  --  recover Unicode from 2006-era Windows-GDI "MSTT" subset fonts.

A THIRD kind of broken Sinhala PDF (after the Type0/Identity-H outline case in
fix_pdf_unicode.py and the FM/DL simple-font case in legacy.py): older Sri-Lankan
Parliament Hansard PDFs embed subsetted *Type1* fonts generated by the Windows
GDI print path. Their BaseFont is an opaque subset id like ``MSTT31c3d8``, they
carry a custom ``/Encoding /Differences`` mapping bytes to code-named glyphs
(``/G7F``, ``/G80`` ...), and they have **no /ToUnicode at all**. The glyph
outlines draw correct Sinhala, but every scrap of Unicode identity has been
stripped: no cmap, no GSUB, no meaningful glyph names. So the file cannot be
self-recovered the way the Type0 files can.

What survives is the byte layout itself, which is a fixed high-byte visual-order
legacy layout (pre-base vowels before the consonant, split vowels, a dual-role
deergha/al stroke, rakaransaya) -- structurally the same family as the FM fonts.
So recovery is, as with FM: a byte -> Unicode-piece table (visual order) plus the
FM reorder/recompose pass, which we reuse wholesale from ``legacy``.

Status: the table below is reverse-engineered from known Hansard front-matter and
body text and covers the common Sinhala glyphs of the ``MSTT31c3d8``-style face.
It is deliberately extensible -- add a byte with the Sinhala piece(s) it draws
(in visual order) and it flows through the reorder automatically. Bold/italic
faces and the Tamil MSTT faces in the same documents need their own tables; runs
this table can't resolve are left untouched rather than mangled.
"""

from . import legacy as _legacy

DEE = _legacy.DEERGHA        # dual-role deergha / al-lakuna sentinel (see legacy)
AU  = _legacy.AU             # au-sign sentinel

# ---------------------------------------------------------------------------
# byte -> Unicode piece(s), in the font's VISUAL order. Pre-base vowel signs are
# emitted as their real Unicode (ෙ ...) and moved by legacy._fm_reorder; the
# deergha byte is emitted as the DEE sentinel and resolved there (long-vowel
# completion vs al-lakuna) exactly as for FM.
# ---------------------------------------------------------------------------
TAB = {
    # independent vowels
    161: "\u0d85",              # අ
    164: "\u0d8b",              # උ
    # consonants
    168: "\u0d9a",              # ක
    170: "\u0d9c",              # ග
    180: "\u0da7",              # ට
    182: "\u0da9",              # ඩ
    184: "\u0dab",              # ණ
    186: "\u0dad",              # ත
    188: "\u0daf",              # ද
    189: "\u0db0",              # ධ
    190: "\u0db1",              # න
    192: "\u0db4",              # ප
    194: "\u0db6",              # බ
    198: "\u0dba",              # ය
    199: "\u0dbb",              # ර
    200: "\u0dbd",              # ල
    201: "\u0dc0",              # ව
    202: "\u0dc1",              # ශ
    203: "\u0dc2",              # ෂ
    204: "\u0dc3",              # ස
    205: "\u0dc4",              # හ
    206: "\u0dc5",              # ළ
    # consonant + dependent-vowel / conjunct ligature glyphs
    134: "\u0da9\u0dca",        # ඩ්
    138: "\u0db8",              # ම
    233: "\u0db8",              # ම   (touching variant, e.g. ත්මක)
    142: "\u0da0\u0dd2",        # චි
    147: "\u0db0\u0dd2",        # ධි
    151: "\u0dc0\u0dd2",        # වි
    215: "\u0dbb\u0dd3",        # රී
    218: "\u0dbb\u0dca",        # ර්   (repaya: ර + virama)
    187: "\u0dca\u0dae",        # ්ථ   (touching, e.g. ස්ථ)
    242: "\u0dca\u200d\u0dbb",  # ්‍ර  rakaransaya
    # dependent vowel signs
    229: "\u0dcf",              # ා
    230: "\u0dd0",              # ැ
    232: "\u0dd2",              # ි
    248: "\u0dd2",              # ි  (contextual variant)
    234: "\u0dd4",              # ු
    235: "\u0dd4",              # ු  (contextual variant)
    236: "\u0dd6",              # ූ
    196: "\u0dd3",              # ී
    251: "\u0dd3",              # ී  (contextual variant)
    # pre-base sign (moved by the reorder), anusvara, and dual-role strokes
    239: "\u0dd9",              # ෙ  (pre-base; long ේ / ො / ෝ resolved via DEE)
    240: AU,                    # ෞ completion (ෙ C AU -> ෞ)
    226: "\u0d82",              # ං  anusvara
    224: DEE,                   # deergha / al-lakuna (dual role, see legacy)
}


def decode_bytes(bs):
    """Show-operand bytes -> the visual-order Unicode-piece string."""
    return "".join(TAB.get(b, chr(b) if b < 128 else "\ufffd") for b in bs)


def transliterate(bs):
    """One GDI/MSTT run's bytes -> logical Unicode Sinhala."""
    text = _legacy._fm_reorder(decode_bytes(bs))
    # a rakaransaya glyph is sometimes followed by an explicit al -> collapse
    return text.replace("\u0dca\u200d\u0dbb\u0dca", "\u0dca\u200d\u0dbb")


def coverage(bs):
    """Fraction of the run's high bytes this table knows (0..1).

    Used to decide whether a run/font is actually the Sinhala family this table
    targets, so Tamil / bold MSTT faces we don't have a table for are skipped
    rather than mangled.
    """
    high = [b for b in bs if b >= 128]
    if not high:
        return 1.0
    known = sum(1 for b in high if b in TAB)
    return known / len(high)